# This workflow runs our tests.

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-server:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.18.1
      uses: actions/setup-node@v2
      with:
        node-version: '14.18.1'
        cache: 'npm'
        cache-dependency-path: './server/package-lock.json'
    - run: |
        npm install --prefix server/
        npm run ci --prefix server/
      
  test-client:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.18.1
      uses: actions/setup-node@v2
      with:
        node-version: '14.18.1'
        cache: 'npm'
        cache-dependency-path: './client/package-lock.json'
    - run: |
        npm install --prefix client/
        npm run ci --prefix client/
